apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: waiting-nginx
  name: waiting-nginx
spec:
  containers:
  - image: nginx
    name: waiting-nginx
    resources: {}
    livenessProbe:
      exec:
        command:
        - 'true'
    readinessProbe:
      exec:
        command:
        - sh
        -  -c
        - 'curl http://my-nginx:80'
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
