# Quando utilizar um Service account para conexão com o AWS Secret Manager deve-se configurar essa estrutura

apiVersion: v1
kind: ServiceAccount
metadata:
  name: nome-da-conta-de-servico-criada-pelo-eksctl-create-iamserviceaccount 
  namespace: ns-da-aplicacao
  annotations:    
    eks.amazonaws.com/role-arn: arn:-da-role-no-IAM
