apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: nome-do-secret-provider-class
  namespace: ns-da-aplicacao
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "arn:aws:secretsmanager:-Objeto-no-aws-secret-manager"
        objectAlias: "aws_secret.ini"