apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: ns-da-aplicacao
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:-do-certificado-para-https"

spec:
  type: LoadBalancer
  selector:
    app: meu-app-k8s
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 80
