apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: myservice
  name: myservice
spec:
  ports:
  - name: 80-9376
    port: 80
    protocol: TCP
    targetPort: 9376
  selector:
    app: myservice
  type: ClusterIP
status:
  loadBalancer: {}
