## Exemplo de aquivo para deploy de secrets com o helm

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ambiente }}-meu-secrets
  namespace: ns-da-aplicacao
stringData:
  database.config: |
    {{- tpl ((.Files.Glob "qa/secrets/database.config").AsConfig) . | nindent 2 }}  