apiVersion: v1
kind: LimitRange
metadata:
  name: limitando-recursos
spec:
  limits:
  - default: # = limit do pod
      cpu: 1
      memory: 100Mi
    defaultRequest: # = ao request do pod
      cpu: 0.5
      memory: 80Mi
    type: Container