apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: pod-01
spec:
  containers:
  - image: nginx:1.18.0
    name: container-1
    ports:
      - containerPort: 80
    volumeMounts:
      - name: workdir
        mountPath: /usr/share/nginx/html

  - image: busybox
    name: container-2
    command: ["sh", "-c", "while true; do uname -a >> /tmp/index.html; date >> /tmp/index.html; sleep 2; done"]
    volumeMounts:
      - name: workdir
        mountPath: /tmp/

  - image: busybox
    name: container-3
    command: ["sh", "-c", "tail -f /tmp/index.html"]
    volumeMounts:
      - name: workdir
        mountPath: /tmp/

  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: workdir
      emptyDir: {}
status: {}
