apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: meu-container-web
  name: meu-container-web
spec:
  containers:
  - image: nginx:1.21.4
    name: meu-container-web
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
