apiVersion: v1
kind: Pod
metadata:
  name: init-demo
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: workdir
      mountPath: /usr/share/nginx/html
  initContainers:
  - name: ini-pod
    image: busybox:1.28
    command: ['wget','-O','/work-dir/index.html','http://linuxtips.io']
    #command: ['sh', '-c', 'until nslookup myservice; do echo waiting for myservice; sleep 2; done;']
    #image: busybox
    #command: ['sh', '-c', 'curl http://linuxtips.io --output /work-dir/index.html']
    #command: ['sh', '-c', 'echo The app is running! && sleep 10']
    # command:
    # - wget
    # - "-O"
    # - "/work-dir/index.html"
    # - http://info.cern.ch
    volumeMounts:
    - name: workdir
      mountPath: "/work-dir"
  dnsPolicy: Default
  volumes:
  - name: workdir
    emptyDir: {}